config/routes.rb
PleadingApp::Application.routes.draw do
  resources :pleading_templates

  resources :pages
  resources :tests do
    collection do
      get 'htmltoword'
    end
  end

  mount Ckeditor::Engine => '/ckeditor'

  root 'pages#index'

end

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>

    <div id="error_explanation" class="alert alert-danger alert-dismissable">
       <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <strong><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</strong>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title , :class => 'form-control col-md-6' %>
  </div>
  <br />
  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content , :class => 'ckeditor_textarea' %>
  </div>
  <div class="actions">
    <%= f.submit :class=> "btn btn-default btn-lg btn-success" %>
    <%= link_to 'Back', pages_path , :class => "btn btn-danger btn-lg" %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<div class="container">
    <h1>Editing page <small><%= link_to 'Download Document', page_path(@page, :format => "docx"), :class => 'btn btn-primary' %></small></h1>
  </div>
  <div class="row">
  <div class= "container">
    <%= render 'form' %>
    </div>
  </div>

    
 

app/views/pages/index.html.erb
<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <h1 class="text-center">Pleading Assembly</h1>
    <div class="table-responsive">
      <table class="table table-condensed">
        <thead>
          <tr>
            <th><h5><strong>Pleading Title</strong></h5></th>
          </tr>
        </thead>

        <tbody>
          <% @pages.each do |page| %>
            <tr>
              <td><%= page. title %></td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td align="center">
                <%= link_to 'Show', page, :class => 'btn btn-success' %>&nbsp;
                <%= link_to 'Edit', edit_page_path(page), :class => 'btn btn-warning' %>&nbsp;
                <%= link_to 'Delete',  page, :class => 'btn btn-danger' , method: :delete, data: { confirm: 'Are you sure?', } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
   <%= link_to 'Create New', new_page_path , :class => 'btn btn-primary' %>
  </div>
</div>

app/views/pages/new.html.erb
<div class="container">
<h1>New page</h1>
</div>
 <div class="row">
  <div class= "container">
    <%= render 'form' %>
    </div>
  </div>

app/views/pages/show.docx.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>


<%= @content.html_safe %>

</body>
</html>

app/views/pages/show.html.erb
<div class="container" style="padding-top: 30px;">
<div class="col-md-12">
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> fade in">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <h5><%= value %></h5>
    </div>
  <% end %>
</div>
<div class="page-header text-center"><h3>Pleading for <small><%= @page.title %></small></h3></div>
<p>
  <%= form_for(@page) do |f| %>
   <%= f.text_area :content , :class => 'ckeditor_textarea' %>
   <% end %>
</p>
<%= link_to 'Download', page_path(@page, :format => "docx") , :class => 'btn btn-primary' %>
<%= link_to 'Edit', edit_page_path(@page), :class => 'btn btn-warning' %>
<%= link_to 'Back', pages_path, :class => 'btn btn-danger' %>

</div>