config/routes.rb
PleadingApp::Application.routes.draw do
  resources :pleading_templates

  resources :pages
  resources :tests do
    collection do
      get 'htmltoword'
    end
  end

  mount Ckeditor::Engine => '/ckeditor'

  root 'pages#index'

end

app/models/pleading_template.rb
class PleadingTemplate < ActiveRecord::Base
  validates :case_heading, :case_title, :case_no, :nature_of_case, :pleadings_intro, :copy_furnished, presence: true
end

app/controllers/pleading_templates_controller.rb
class PleadingTemplatesController < ApplicationController
  before_action :set_pleading_template, only: [:show, :edit, :update, :destroy]

  # GET /pleading_templates
  # GET /pleading_templates.json
  def index
    @pleading_templates = PleadingTemplate.all
  end

  # GET /pleading_templates/1
  # GET /pleading_templates/1.json
  def show
    @pleading_templates = PleadingTemplate.all
    params[:complete] = "#{@pleading_template.case_heading}
                          #{@pleading_template.case_title}
                          #{@pleading_template.case_no}
                          #{@pleading_template.nature_of_case}
                          #{@pleading_template.pleadings_intro}
                          #{@pleading_template.copy_furnished}";
                 
    @complete_content = params[:complete]


    respond_to do |format|
      format.html

      format.docx do
        set_header('docx', "#{@pleading_template.id}.docx")   
        @content_for_docx = params[:complete]
      end
    end

  end

  # GET /pleading_templates/new
  def new
    @pleading_template = PleadingTemplate.new
  end

  # GET /pleading_templates/1/edit
  def edit
  end

  # POST /pleading_templates
  # POST /pleading_templates.json
  def create
    @pleading_template = PleadingTemplate.new(pleading_template_params)

    respond_to do |format|
      if @pleading_template.save
        format.html { redirect_to @pleading_template, notice: 'Pleading template was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pleading_template }
      else
        format.html { render action: 'new' }
        format.json { render json: @pleading_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pleading_templates/1
  # PATCH/PUT /pleading_templates/1.json
  def update
    respond_to do |format|
      if @pleading_template.update(pleading_template_params)
        format.html { redirect_to @pleading_template, notice: 'Pleading template was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pleading_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pleading_templates/1
  # DELETE /pleading_templates/1.json
  def destroy
    @pleading_template.destroy
    respond_to do |format|
      format.html { redirect_to pleading_templates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pleading_template
      @pleading_template = PleadingTemplate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pleading_template_params
      params.require(:pleading_template).permit(:case_heading, :case_title, :case_no, :nature_of_case, :pleadings_intro, :copy_furnished)
    end
end

app/helpers/pleading_templates_helper.rb
module PleadingTemplatesHelper
end

app/views/pleading_templates/_form.html.erb
<%= form_for(@pleading_template) do |f| %>
  <% if @pleading_template.errors.any? %>

    <div id="error_explanation" class="alert alert-danger alert-dismissable">
       <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <strong><%= pluralize(@pleading_template.errors.count, "error") %> prohibited this page from being saved:</strong>

      <ul>
      <% @pleading_template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :case_heading %><br>
    <%= f.text_area :case_heading, :class => 'ckeditor_textarea' %>
  </div>
  <div class="form-group">
    <%= f.label :case_title %><br>
    <%= f.text_area :case_title, :class => 'ckeditor_textarea' %>
  </div>
  <div class="form-group">
    <%= f.label :case_no %><br>
    <%= f.text_area :case_no, :class => 'ckeditor_textarea' %>
  </div>
  <div class="form-group">
    <%= f.label :nature_of_case %><br>
    <%= f.text_area :nature_of_case, :class => 'ckeditor_textarea' %>
  </div>
  <div class="form-group">
    <%= f.label :pleadings_intro %><br>
    <%= f.text_area :pleadings_intro, :class => 'ckeditor_textarea' %>
  </div>
  <div class="form-group">
    <%= f.label :copy_furnished %><br>
    <%= f.text_area :copy_furnished, :class => 'ckeditor_textarea' %>
  </div>
    <div class="actions">
    <%= f.submit :class=> "btn btn-default btn-lg btn-success" %>
    <%= link_to 'Back', pleading_templates_path , :class => "btn btn-danger btn-lg" %>
  </div>
<% end %>

app/views/pleading_templates/edit.html.erb
<div class="container">
    <h1>Editing Pleading Templates</h1>
  </div>

  <div class="row">
  <div class= "container">
    <%= render 'form' %>
    </div>
  </div>

app/views/pleading_templates/index.html.erb
<div class="container">
  <div class="col-md-10">
    <h1 class="text-center">Pleading Templates</h1>
    <div class="table-responsive">
      <table class="table table-condensed">
        <thead>
          <tr>
            <th>Case ID</th>
            <th>Case Title</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
          </tr>
        </thead>
        <tbody>
          <% @pleading_templates.each do |pleading_template| %>
            <tr>
              <td><%= pleading_template.id %></td>
              <td><%= pleading_template.case_heading.html_safe %></td>
              <td> <%= link_to 'Show', pleading_template, :class => 'btn btn-success' %></td>
              <td><%= link_to 'Edit', edit_pleading_template_path(pleading_template), :class => 'btn btn-warning' %></td>
              <td><%= link_to 'Delete',  pleading_template, :class => 'btn btn-danger' , method: :delete, data: { confirm: 'Are you sure?', } %></td>
              <td>&nbsp;</td>
              
            </tr>
          <% end %>
        </tbody>

      </table>
    </div>
   <%= link_to 'New Pleading template', new_pleading_template_path , :class => 'btn btn-primary' %>
  </div>
</div>

app/views/pleading_templates/new.html.erb
<div class="container">
  <h1>New Pleading Templates</h1>
</div>

  <div class="row">
    <div class= "container">
      <div class="col-md-8 col-md-offset-2">
        <%= render 'form' %>
      </div>
    </div>
  </div>

app/views/pleading_templates/show.doc.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>


<%= @content_for_docx.html_safe %>

</body>
</html>

app/views/pleading_templates/show.docx.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>


<%= @content_for_docx.html_safe %>

</body>
</html>

app/views/pleading_templates/show.html.erb
<div class="container">
    <h1>Your Finished Document</h1>
  </div>

  <div class="row">
  <div class= "container">
    <textarea cols="20" rows="40" id="post_body" name="post[body]" class="ckeditor_textarea">
      <%= @complete_content %>
    </textarea>
    <br />
    <%= link_to 'Download', pleading_template_path(@pleading_template, :format => "docx") , :class => 'btn btn-primary btn-lg' %>
    <%= link_to 'Edit', edit_pleading_template_path(@pleading_template), :class => 'btn btn-warning btn-lg' %> 
    <%= link_to 'Back', pleading_templates_path, :class => 'btn btn-danger btn-lg' %>
    </div>
  </div>